name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: see current files in directory
      run: |
        ls -la LibrarieProiect
    - name: Build Docker Image
      run: |
        docker build -t my_python_tests -f LibrarieProiect/dockerfile .
        
  
